# -*- ruby -*-

require 'tempfile'

task :default => :build

PANDOC_HTML_OPTS = [
  '-i',
  '--self-contained',
  '-t', 'slidy',
  '--smart'
]

task :build => :html

task :html => :css do
  tmp = Tempfile.new('slides')
  tmp.close
  begin
    args = PANDOC_HTML_OPTS + ['-s', 'slides.md', '-o', tmp.path]
    sh 'pandoc', *args
    puts "Inserting custom stylesheet and generating index.html"
    File.open("index.html", "w") do |out|
      File.open(tmp.path).each do |line|
        if line =~ %r{^</head>}
          custom_css = File.open('custom.css').read
          out.write <<-EOF
<style type="text/css">
#{custom_css}
</style>
          EOF
        end
        out.write(line)
      end
    end
  ensure
    tmp.unlink
  end
end

task :css => 'custom.css'

file 'custom.css' => ['custom.less'] do
  sh 'sh', '-c', 'lessc custom.less >custom.css'
end

task :clean do
  %w{combined.tex *.aux *.vrb *.out *.log custom.css index.html}.each do |pat|
    Dir.glob(pat).each do |i|
      rm_f i
    end
  end
end
